### ISSUE TITLE
Supposed bug

### ISSUE THREAD

**Issue by dpardons** [TLWebdesign/pretty-buttons#1]
PHP 7.4.29
Joomla 4.1.5
---------------------
Button trouble: not displayed with following error for each button:
Notice: Undefined property: stdClass::$text in C:\laragon\www\joomla4\modules\mod_prettybuttons\tmpl\default.php on line 28

ex: module with 1 buttons
Pretty Buttons

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare nibh luctus nisl fringilla aliquam. Maecenas mauris magna, hendrerit a tincidunt at, dictum vel ipsum.

Notice: Undefined property: stdClass::$text in C:\laragon\www\joomla4\modules\mod_prettybuttons\tmpl\default.php on line 28

Maecenas sagittis ac nisl vitae tempor. Maecenas eu quam ornare orci pharetra imperdiet. 

Regards
Daniel

**Comment by dpardons** [comment]
Hi
After a short investigation, correct line 29 with following statement:
                if ($button->url && ($button->iconclass || $button->buttontext)) :
replacing $button->text by $button->buttontext
Regards
Daniel

**Comment by TLWebdesign** [comment]
Hi, thanks for reporting this. yes i'd changed the name of the field to better reflect what it was when i changed language strings must've missed some. Will change it thanks!
